import fs from "node:fs";
const app = fs.readFileSync("src/App_nuovo.jsx", "utf8");
const dashboard = fs.readFileSync("src/pages/DashboardPage.jsx", "utf8");
const build = JSON.parse(fs.readFileSync("public/fmed-build.json", "utf8"));
const pkg = JSON.parse(fs.readFileSync("package.json", "utf8"));
const version = "FMED_ENTERPRISE_1_0_E7_2_OPERATIONAL_WINDOW_ARCHIVE_2026_07_19";
if (!app.includes(version)) throw new Error("Versione E7.1 assente in App_nuovo.jsx");
if (!app.includes("FMED ENTERPRISE 1.0 · E7.2 FINESTRA OPERATIVA E ARCHIVIO STORICO")) throw new Error("Build label E7.1 assente");
if (!dashboard.includes("/dashboard-enterprise")) throw new Error("Endpoint Dashboard Enterprise non collegato");
if (build.build !== version) throw new Error("fmed-build.json non allineato a E7.1");
if (pkg.version !== "7.1.0") throw new Error("package.json non allineato a E7.1");
console.log("FMED E7.2 release finale: OK");
