import assert from "node:assert/strict";
import fs from "node:fs";
const app = fs.readFileSync("src/App_nuovo.jsx", "utf8");
const dash = fs.readFileSync("src/pages/DashboardPage.jsx", "utf8");
const settings = fs.readFileSync("src/ImpostazioniPage.jsx", "utf8");
const css = fs.readFileSync("src/FmedE81OperationalSimplified.css", "utf8");
const build = JSON.parse(fs.readFileSync("public/fmed-build.json", "utf8"));
assert.match(app, /E8_1_OPERATIVO_SEMPLIFICATO/);
assert.match(app, /E8\.1 OPERATIVO SEMPLIFICATO/);
assert.match(app, /const FMED_ALL_MENU_ITEMS = \["Dashboard", "Asset", "Interventi", "Scadenze", "Infrastrutture", "Sicurezza 81\/08", "Gestione Utenti"\]/);
assert.doesNotMatch(app, /const FMED_ALL_MENU_ITEMS = \[[^\]]*"Processi"/);
assert.match(dash, /Cosa richiede attenzione e cosa devi fare oggi/);
assert.match(dash, /Automazioni attive/);
assert.match(dash, /advancedOpen/);
assert.match(settings, /Strumenti e impostazioni/);
assert.match(settings, /Motore Cicli, Catalogo Canonico/);
assert.ok(css.length > 3000);
assert.equal(build.release, "E8.1 Operativo Semplificato");
console.log("FMED E8.1 Operativo Semplificato frontend: OK");
