/* FMED Enterprise 1.0 · E8.2.3 LIGHT ONLY
   Registro consolidato degli stili inline effettivamente utilizzati dal frontend.
   Contiene esclusivamente la configurazione grafica chiara attiva. */

const styles = {
  "actionBtnDelete": {
    "height": "34px",
    "minWidth": 92,
    "padding": "0 12px",
    "borderRadius": 10,
    "border": "1px solid rgba(255,91,104,.48)",
    "background": "rgba(220,53,69,.12)",
    "color": "#FF5B68",
    "fontSize": 11,
    "fontWeight": 950,
    "cursor": "pointer",
    "whiteSpace": "nowrap",
    "display": "inline-flex",
    "alignItems": "center",
    "justifyContent": "center",
    "minHeight": 40,
    "boxShadow": "none",
    "letterSpacing": ".035em",
    "textTransform": "uppercase"
  },
  "actionBtnEdit": {
    "height": "34px",
    "minWidth": 92,
    "padding": "0 12px",
    "borderRadius": 10,
    "border": "1px solid var(--fmed-border)",
    "background": "rgba(8,26,40,.92)",
    "color": "var(--fmed-text)",
    "fontSize": 11,
    "fontWeight": 950,
    "cursor": "pointer",
    "whiteSpace": "nowrap",
    "display": "inline-flex",
    "alignItems": "center",
    "justifyContent": "center",
    "lineHeight": 1,
    "WebkitTextFillColor": "var(--fmed-primary)",
    "minHeight": 40,
    "gap": 6,
    "boxShadow": "none",
    "letterSpacing": ".035em",
    "textTransform": "uppercase"
  },
  "app": {
    "display": "flex",
    "width": "100vw",
    "height": "100vh",
    "color": "var(--fmed-text)",
    "fontFamily": "'Futura', 'Futura PT', 'Jost', 'Century Gothic', Arial, sans-serif",
    "overflow": "hidden",
    "background": "var(--fmed-main-bg)",
    "letterSpacing": ".01em"
  },
  "assetActionBtn": {
    "minHeight": "54px",
    "borderRadius": "12px",
    "border": "1px solid var(--fmed-border)",
    "background": "var(--fmed-surface-solid)",
    "color": "var(--fmed-text)",
    "fontWeight": 500,
    "fontSize": "13px",
    "fontFamily": "\"Futura Light\", \"Futura PT\", Futura, \"Trebuchet MS\", Arial, sans-serif",
    "cursor": "pointer",
    "display": "flex",
    "alignItems": "center",
    "justifyContent": "center",
    "gap": "9px",
    "padding": "8px 12px",
    "whiteSpace": "nowrap",
    "overflow": "hidden",
    "textAlign": "center",
    "lineHeight": 1.16,
    "minWidth": 0,
    "letterSpacing": ".05em",
    "boxShadow": "none",
    "overflowWrap": "anywhere"
  },
  "assetActionBtnDelete": {
    "background": "linear-gradient(135deg,#C98A7D 0%,#B9776A 100%)",
    "color": "#fff",
    "border": "none"
  },
  "assetActionBtnEdit": {
    "background": "linear-gradient(135deg,#8F9E8B 0%,#7C8B79 100%)",
    "color": "#fff",
    "border": "none"
  },
  "assetActionBtnPrimary": {
    "border": "none",
    "background": "linear-gradient(135deg,#169C8F,#165A52)",
    "color": "#FFFFFF"
  },
  "assetActionIcon": {
    "fontSize": "19px",
    "lineHeight": 1
  },
  "assetActionsCode": {
    "padding": "10px 14px",
    "borderRadius": "14px",
    "background": "var(--fmed-surface-solid)",
    "border": "1px solid var(--fmed-border)",
    "color": "var(--fmed-soft-btn-text)",
    "fontWeight": 400,
    "fontSize": "14px",
    "whiteSpace": "nowrap"
  },
  "assetActionsGroupBlock": {
    "padding": "16px",
    "borderRadius": "12px",
    "background": "rgba(31,174,156,.05)",
    "border": "1px solid rgba(31,174,156,.16)",
    "boxShadow": "none",
    "color": "#F7F9FB"
  },
  "assetActionsGroupGrid": {
    "display": "grid",
    "gap": "10px",
    "minWidth": 0,
    "gridTemplateColumns": "repeat(auto-fit, minmax(170px, 1fr))"
  },
  "assetActionsGroupTitle": {
    "marginBottom": "10px",
    "color": "var(--fmed-muted)",
    "fontSize": "12px",
    "fontWeight": 500,
    "letterSpacing": ".05em",
    "textTransform": "uppercase"
  },
  "assetActionsGrouped": {
    "display": "grid",
    "gridTemplateColumns": "repeat(2, minmax(0, 1fr))",
    "gap": "14px",
    "alignItems": "stretch"
  },
  "assetActionsHeaderCompact": {
    "display": "flex",
    "alignItems": "center",
    "justifyContent": "space-between",
    "gap": "14px",
    "marginBottom": "12px"
  },
  "assetActionsPanel": {
    "background": "var(--fmed-surface-solid)",
    "border": "1px solid rgba(20,32,51,.08)",
    "borderRadius": "12px",
    "padding": "18px",
    "boxShadow": "0 3px 10px rgba(15,23,42,.04)",
    "marginTop": "10px",
    "marginBottom": "12px"
  },
  "assetActionsSubtitle": {
    "margin": "6px 0 0 0",
    "fontSize": "13px",
    "color": "var(--fmed-muted)",
    "fontWeight": 400
  },
  "assetActionsTitle": {
    "margin": 0,
    "fontSize": "16px",
    "fontWeight": 400,
    "color": "var(--fmed-text)",
    "letterSpacing": "-0.02em"
  },
  "assetHeroCard": {
    "display": "flex",
    "alignItems": "center",
    "justifyContent": "space-between",
    "gap": "14px",
    "background": "var(--fmed-surface-solid)",
    "border": "1px solid rgba(20,32,51,.08)",
    "borderRadius": "12px",
    "padding": "18px",
    "marginBottom": "8px",
    "boxShadow": "0 3px 10px rgba(15,23,42,.04)"
  },
  "assetHeroCode": {
    "fontSize": "29px",
    "lineHeight": "31px",
    "fontWeight": 400,
    "color": "var(--fmed-text)",
    "letterSpacing": "-1px"
  },
  "assetHeroIcon": {
    "width": "48px",
    "height": "48px",
    "borderRadius": "17px",
    "background": "linear-gradient(135deg,#8F9E8B 0%,#7C8B79 100%)",
    "color": "#fff",
    "display": "flex",
    "alignItems": "center",
    "justifyContent": "center",
    "fontSize": "22px",
    "boxShadow": "0 12px 24px rgba(143,158,139,.24)"
  },
  "assetHeroLabel": {
    "fontSize": "13px",
    "fontWeight": 400,
    "color": "#2b4770",
    "textTransform": "uppercase",
    "letterSpacing": ".4px"
  },
  "assetHeroLeft": {
    "flex": 1,
    "minWidth": 0,
    "gap": 7,
    "display": "flex",
    "flexDirection": "column",
    "justifyContent": "center"
  },
  "assetHistoryCollapsible": {
    "marginTop": "22px",
    "borderRadius": "12px",
    "border": "1px solid rgba(31,174,156,.22)",
    "background": "linear-gradient(145deg, rgba(8,28,43,.96), rgba(5,18,30,.97))",
    "boxShadow": "0 4px 14px rgba(0,0,0,.05)",
    "padding": "20px",
    "color": "#F7F9FB",
    "maxWidth": "100%",
    "overflow": "hidden"
  },
  "assetHistoryHeaderCompact": {
    "display": "flex",
    "alignItems": "center",
    "justifyContent": "space-between",
    "gap": "18px",
    "marginBottom": "0"
  },
  "assetHistorySubtitle": {
    "margin": "3px 0 0 0",
    "fontSize": "14px",
    "color": "var(--fmed-muted)",
    "fontWeight": 400
  },
  "assetHistoryTitle": {
    "margin": 0,
    "fontSize": "21px",
    "fontWeight": 400,
    "color": "var(--fmed-text)"
  },
  "assetInfoTable": {
    "display": "grid",
    "gridTemplateColumns": "1fr",
    "gap": 0
  },
  "assetKpiIconBlue": {
    "width": "36px",
    "height": "36px",
    "borderRadius": "14px",
    "display": "flex",
    "alignItems": "center",
    "justifyContent": "center",
    "fontSize": "16px",
    "background": "#eaf2ff"
  },
  "assetKpiIconGreen": {
    "width": "36px",
    "height": "36px",
    "borderRadius": "14px",
    "display": "flex",
    "alignItems": "center",
    "justifyContent": "center",
    "fontSize": "16px",
    "background": "#e7f8ef"
  },
  "assetKpiIconOrange": {
    "width": "36px",
    "height": "36px",
    "borderRadius": "14px",
    "display": "flex",
    "alignItems": "center",
    "justifyContent": "center",
    "fontSize": "16px",
    "background": "var(--fmed-surface-soft)"
  },
  "assetKpiIconPurple": {
    "width": "36px",
    "height": "36px",
    "borderRadius": "14px",
    "display": "flex",
    "alignItems": "center",
    "justifyContent": "center",
    "fontSize": "16px",
    "background": "#f1e9ff"
  },
  "assetKpiItem": {
    "display": "flex",
    "alignItems": "center",
    "gap": "10px",
    "padding": "6px 12px",
    "borderRight": "1px solid #dbe8f7"
  },
  "assetKpiLabel": {
    "color": "var(--fmed-d3-muted)",
    "fontSize": 12,
    "fontWeight": 500,
    "textTransform": "uppercase",
    "letterSpacing": ".08em",
    "lineHeight": "13px",
    "WebkitTextFillColor": "var(--fmed-d3-muted)"
  },
  "assetKpiRibbon": {
    "display": "grid",
    "gridTemplateColumns": "repeat(5, 1fr)",
    "gap": "0",
    "background": "var(--fmed-surface-solid)",
    "border": "1px solid var(--fmed-border)",
    "borderRadius": "19px",
    "padding": "6px 10px",
    "marginBottom": "8px",
    "boxShadow": "0 10px 24px rgba(0,31,91,.055)"
  },
  "assetKpiValue": {
    "display": "block",
    "color": "var(--fmed-d3-title)",
    "fontSize": "clamp(30px, 2vw, 38px)",
    "lineHeight": 1.05,
    "fontWeight": 500,
    "letterSpacing": "-.04em",
    "marginTop": 12,
    "WebkitTextFillColor": "var(--fmed-d3-title)"
  },
  "assetKpiValueSmall": {
    "marginTop": "2px",
    "fontSize": "15px",
    "fontWeight": 400,
    "color": "var(--fmed-text)"
  },
  "assetMainGrid": {
    "display": "grid",
    "gridTemplateColumns": "repeat(auto-fit, minmax(min(100%, 340px), 1fr))",
    "gap": "14px",
    "alignItems": "stretch",
    "marginBottom": "12px"
  },
  "assetPanel": {
    "background": "var(--fmed-surface-solid)",
    "border": "1px solid rgba(20,32,51,.08)",
    "borderRadius": "12px",
    "padding": "18px",
    "boxShadow": "0 3px 10px rgba(15,23,42,.04)",
    "overflow": "hidden"
  },
  "cancelBtn": {
    "padding": "14px 20px",
    "borderRadius": "14px",
    "border": "1px solid rgba(31,174,156,.24)",
    "background": "rgba(255,255,255,.05)",
    "color": "#F7F9FB",
    "fontWeight": 500,
    "cursor": "pointer",
    "minHeight": "44px",
    "fontSize": "13px",
    "lineHeight": "16px",
    "letterSpacing": ".05em",
    "whiteSpace": "normal",
    "boxShadow": "none"
  },
  "card": {
    "width": "100%",
    "boxSizing": "border-box",
    "background": "var(--fmed-card-gradient)",
    "border": "1px solid var(--fmed-border)",
    "borderRadius": 24,
    "padding": "20px",
    "boxShadow": "var(--fmed-card-shadow-soft)",
    "overflow": "hidden",
    "color": "var(--fmed-text)",
    "maxWidth": "100%",
    "WebkitTextFillColor": "var(--fmed-text)"
  },
  "closeBtn": {
    "position": "absolute",
    "top": "22px",
    "right": "22px",
    "height": "42px",
    "minWidth": "86px",
    "borderRadius": "14px",
    "border": "1px solid rgba(31,174,156,.24)",
    "background": "rgba(255,255,255,.05)",
    "color": "#F7F9FB",
    "fontWeight": 500,
    "fontFamily": "\"Futura Light\", \"Futura PT\", Futura, \"Trebuchet MS\", Arial, sans-serif",
    "cursor": "pointer",
    "boxShadow": "none",
    "minHeight": "46px",
    "fontSize": "12px",
    "letterSpacing": ".05em"
  },
  "detailItem": {
    "display": "grid",
    "gridTemplateColumns": "128px 1fr",
    "alignItems": "center",
    "padding": "12px",
    "borderBottom": "1px solid var(--fmed-border)",
    "minHeight": "22px",
    "borderRadius": "12px"
  },
  "detailLabel": {
    "fontSize": "11px",
    "color": "#64748b",
    "fontWeight": 500,
    "letterSpacing": ".05em"
  },
  "detailValue": {
    "fontSize": "13px",
    "color": "var(--fmed-text)",
    "fontWeight": 400,
    "wordBreak": "break-word",
    "lineHeight": "18px"
  },
  "dictionaryAccordionBadge": {
    "border": "1px solid var(--fmed-border)",
    "background": "var(--fmed-surface-soft)",
    "color": "var(--fmed-muted)",
    "borderRadius": "999px",
    "padding": "4px 9px",
    "fontSize": "10px",
    "fontWeight": 400,
    "textTransform": "uppercase"
  },
  "dictionaryAccordionChevron": {
    "color": "var(--fmed-accent)",
    "fontSize": "12px",
    "fontWeight": 400
  },
  "dictionaryAccordionContent": {
    "marginTop": "14px",
    "paddingTop": "14px",
    "borderTop": "1px solid var(--fmed-border)"
  },
  "dictionaryAccordionHeader": {
    "width": "100%",
    "border": "none",
    "background": "transparent",
    "color": "var(--fmed-text)",
    "display": "flex",
    "alignItems": "center",
    "justifyContent": "space-between",
    "gap": "12px",
    "cursor": "pointer",
    "textAlign": "left",
    "padding": "4px 2px",
    "fontFamily": "\"Futura Light\", \"Futura PT\", Futura, \"Trebuchet MS\", Arial, sans-serif"
  },
  "dictionaryAccordionIcon": {
    "width": "34px",
    "height": "34px",
    "borderRadius": "12px",
    "background": "var(--fmed-surface-soft)",
    "border": "1px solid var(--fmed-border)",
    "display": "flex",
    "alignItems": "center",
    "justifyContent": "center",
    "color": "var(--fmed-accent)",
    "fontWeight": 400,
    "flex": "0 0 auto"
  },
  "dictionaryAccordionLeft": {
    "display": "flex",
    "alignItems": "center",
    "gap": "12px",
    "minWidth": 0
  },
  "dictionaryAccordionRight": {
    "display": "flex",
    "alignItems": "center",
    "gap": "8px",
    "flex": "0 0 auto"
  },
  "dictionaryAccordionSubtitle": {
    "marginTop": "4px",
    "color": "var(--fmed-muted)",
    "fontSize": "11px",
    "fontWeight": 400
  },
  "dictionaryAccordionTitle": {
    "margin": 0,
    "fontSize": "15px",
    "lineHeight": 1.15,
    "color": "var(--fmed-text)",
    "fontWeight": 400
  },
  "dictionaryBox": {
    "background": "var(--fmed-surface-solid)",
    "border": "1px solid rgba(0,0,0,.08)",
    "borderRadius": "12px",
    "padding": "20px",
    "boxShadow": "0 4px 14px rgba(0,0,0,.05)",
    "minHeight": "auto",
    "boxSizing": "border-box",
    "overflow": "hidden"
  },
  "dictionaryBoxOpen": {
    "boxShadow": "0 18px 38px rgba(0,31,91,.10)"
  },
  "dictionaryChip": {
    "border": "1px solid var(--fmed-border)",
    "background": "var(--fmed-surface-soft)",
    "color": "var(--fmed-text)",
    "borderRadius": "999px",
    "padding": "5px 6px 5px 10px",
    "fontSize": "10.5px",
    "fontWeight": 400,
    "display": "inline-flex",
    "alignItems": "center",
    "gap": "5px",
    "maxWidth": "calc(100% - 4px)",
    "minWidth": 0
  },
  "dictionaryChipCancel": {
    "width": "24px",
    "height": "24px",
    "borderRadius": "999px",
    "border": "1px solid #d6dff2",
    "background": "#f6f8fc",
    "color": "#33405f",
    "fontWeight": 400,
    "cursor": "pointer"
  },
  "dictionaryChipEdit": {
    "width": "18px",
    "height": "18px",
    "borderRadius": "999px",
    "border": "1px solid #b9c7ff",
    "background": "#f1f4ff",
    "color": "#78684F",
    "fontSize": "11px",
    "lineHeight": "16px",
    "fontWeight": 400,
    "cursor": "pointer",
    "display": "inline-flex",
    "alignItems": "center",
    "justifyContent": "center",
    "padding": 0
  },
  "dictionaryChipEditing": {
    "borderRadius": "14px",
    "padding": "6px",
    "width": "100%",
    "background": "var(--fmed-surface-solid)"
  },
  "dictionaryChipRemove": {
    "width": "18px",
    "height": "18px",
    "borderRadius": "999px",
    "border": "1px solid #ffb5bd",
    "background": "var(--fmed-danger-bg)",
    "color": "#d81725",
    "fontSize": "14px",
    "fontWeight": 400,
    "lineHeight": "14px",
    "cursor": "pointer",
    "display": "inline-flex",
    "alignItems": "center",
    "justifyContent": "center",
    "padding": 0
  },
  "dictionaryChipSave": {
    "width": "24px",
    "height": "24px",
    "borderRadius": "999px",
    "border": "1px solid #8fe5b6",
    "background": "#eafff3",
    "color": "#087b3d",
    "fontWeight": 400,
    "cursor": "pointer"
  },
  "dictionaryChipText": {
    "maxWidth": "190px",
    "overflow": "hidden",
    "textOverflow": "ellipsis",
    "whiteSpace": "nowrap",
    "minWidth": 0
  },
  "dictionaryGrid": {
    "display": "grid",
    "gridTemplateColumns": "repeat(auto-fit, minmax(360px, 1fr))",
    "gap": "14px",
    "alignItems": "start"
  },
  "dictionaryInlineInput": {
    "flex": 1,
    "minWidth": "120px",
    "border": "1px solid #b9c7ff",
    "borderRadius": "10px",
    "padding": "7px 9px",
    "fontSize": "12px",
    "fontWeight": 400,
    "color": "var(--fmed-text)",
    "outline": "none"
  },
  "dictionaryPreview": {
    "display": "flex",
    "flexWrap": "wrap",
    "gap": "7px",
    "marginTop": "12px",
    "maxHeight": "78px",
    "overflowY": "auto",
    "overflowX": "hidden",
    "paddingRight": "6px",
    "alignContent": "flex-start"
  },
  "docBtn": {
    "height": "34px",
    "minWidth": 98,
    "padding": "0 12px",
    "borderRadius": 10,
    "border": "1px solid var(--fmed-border)",
    "background": "rgba(8,26,40,.92)",
    "color": "var(--fmed-text)",
    "fontSize": 11,
    "fontWeight": 950,
    "cursor": "pointer",
    "whiteSpace": "nowrap",
    "display": "inline-flex",
    "alignItems": "center",
    "justifyContent": "center",
    "minHeight": 40,
    "lineHeight": 1,
    "letterSpacing": ".035em",
    "textTransform": "uppercase",
    "fontStyle": "normal",
    "boxSizing": "border-box",
    "maxWidth": "90px",
    "overflow": "hidden"
  },
  "docBtnDisabled": {
    "height": "34px",
    "minWidth": 98,
    "padding": "0 12px",
    "borderRadius": 10,
    "border": "1px solid var(--fmed-border)",
    "background": "rgba(8,26,40,.65)",
    "color": "var(--fmed-muted)",
    "fontSize": 11,
    "fontWeight": 950,
    "cursor": "help",
    "whiteSpace": "nowrap",
    "minHeight": 40,
    "lineHeight": "16px",
    "letterSpacing": ".05em",
    "textTransform": "uppercase",
    "fontStyle": "normal",
    "boxSizing": "border-box",
    "maxWidth": "90px",
    "overflow": "hidden"
  },
  "editActions": {
    "display": "grid",
    "gridTemplateColumns": "1fr 1fr",
    "gap": "10px",
    "marginTop": "24px",
    "flexWrap": "wrap"
  },
  "editField": {
    "display": "flex",
    "flexDirection": "column",
    "gap": "8px"
  },
  "editGrid": {
    "display": "grid",
    "gridTemplateColumns": "repeat(auto-fit, minmax(240px, 1fr))",
    "gap": 14,
    "minWidth": 0
  },
  "editInput": {
    "width": "100%",
    "minHeight": 44,
    "borderRadius": 14,
    "border": "1px solid var(--fmed-border)",
    "padding": "10px 12px",
    "fontFamily": "\"Futura Light\", \"Futura PT\", Futura, \"Trebuchet MS\", Arial, sans-serif",
    "fontWeight": 700,
    "color": "var(--fmed-text)",
    "boxSizing": "border-box",
    "background": "var(--fmed-surface-solid)",
    "fontSize": 15,
    "boxShadow": "none"
  },
  "editLabel": {
    "fontSize": "11px",
    "fontWeight": 800,
    "color": "#7FE2CC",
    "textTransform": "uppercase",
    "lineHeight": "13px",
    "letterSpacing": ".11em"
  },
  "editPanel": {
    "width": "100%",
    "marginTop": "22px",
    "padding": "20px",
    "borderRadius": "22px",
    "background": "linear-gradient(145deg, rgba(8,28,43,.96), rgba(5,18,30,.97))",
    "border": "1px solid rgba(31,174,156,.22)",
    "boxShadow": "0 18px 44px rgba(0,0,0,.32)",
    "boxSizing": "border-box",
    "color": "#F7F9FB"
  },
  "editTextarea": {
    "width": "100%",
    "minHeight": 96,
    "borderRadius": 14,
    "border": "1px solid var(--fmed-border)",
    "padding": "10px 12px",
    "fontFamily": "\"Futura Light\", \"Futura PT\", Futura, \"Trebuchet MS\", Arial, sans-serif",
    "fontWeight": 700,
    "color": "var(--fmed-text)",
    "boxSizing": "border-box",
    "background": "var(--fmed-surface-solid)",
    "fontSize": 15,
    "lineHeight": "18px",
    "boxShadow": "none"
  },
  "exportCheckLabel": {
    "display": "flex",
    "alignItems": "center",
    "gap": "7px",
    "fontSize": "11px",
    "fontWeight": 400,
    "color": "var(--fmed-text)",
    "background": "var(--fmed-surface-solid)",
    "border": "1px solid #e1ebf7",
    "borderRadius": "10px",
    "padding": "7px 8px",
    "cursor": "pointer"
  },
  "exportCheckboxGrid": {
    "display": "grid",
    "gridTemplateColumns": "repeat(2, minmax(0, 1fr))",
    "gap": "7px 10px",
    "maxHeight": "116px",
    "overflowY": "auto",
    "paddingRight": "4px"
  },
  "exportFilterBox": {
    "marginTop": "12px",
    "border": "1px solid var(--fmed-border)",
    "borderRadius": "14px",
    "background": "var(--fmed-surface-soft)",
    "padding": "12px"
  },
  "fmeaBox": {
    "border": "1px solid var(--fmed-border)",
    "borderRadius": "14px",
    "background": "var(--fmed-card-gradient)",
    "minHeight": "138px",
    "display": "flex",
    "flexDirection": "column",
    "alignItems": "center",
    "justifyContent": "center",
    "gap": "7px",
    "padding": "16px 12px",
    "textAlign": "center",
    "color": "var(--fmed-text)",
    "fontSize": "15px",
    "transition": "transform .18s ease, box-shadow .18s ease"
  },
  "fmeaGrid": {
    "display": "grid",
    "gridTemplateColumns": "1fr 1fr",
    "gap": "11px",
    "height": "calc(100% - 32px)"
  },
  "historyFilterBar": {
    "display": "flex",
    "alignItems": "center",
    "gap": "12px",
    "flexWrap": "wrap",
    "paddingTop": "18px",
    "marginTop": "16px",
    "borderTop": "1px solid #E5EEF9"
  },
  "historyResultInfo": {
    "marginTop": "12px",
    "color": "var(--fmed-muted)",
    "fontSize": "12px",
    "fontWeight": 400
  },
  "input": {
    "height": "42px",
    "padding": "10px 12px",
    "borderRadius": 13,
    "border": "1px solid var(--fmed-border)",
    "background": "var(--fmed-surface-solid)",
    "color": "var(--fmed-text)",
    "fontSize": "13px",
    "outline": "none",
    "boxShadow": "inset 0 1px 0 rgba(255,255,255,.035)",
    "textTransform": "none",
    "fontStyle": "normal",
    "minWidth": 0,
    "boxSizing": "border-box",
    "minHeight": 42,
    "fontWeight": 720,
    "width": "100%"
  },
  "linkEditActions": {
    "display": "flex",
    "gap": "10px",
    "marginTop": "12px",
    "flexWrap": "wrap"
  },
  "linkEditBox": {
    "width": "100%",
    "marginTop": "16px",
    "padding": "18px",
    "borderRadius": "18px",
    "border": "1px solid rgba(31,174,156,.18)",
    "background": "rgba(31,174,156,.055)",
    "boxSizing": "border-box",
    "color": "#F7F9FB"
  },
  "main": {
    "flex": "1 1 auto",
    "height": "100vh",
    "padding": "22px 26px 34px",
    "boxSizing": "border-box",
    "overflow": "auto",
    "backgroundColor": "#F5F1E8",
    "backgroundImage": "var(--fmed-main-bg)",
    "backgroundSize": "cover",
    "backgroundPosition": "center bottom",
    "backgroundRepeat": "no-repeat",
    "background": "transparent",
    "gap": "16px",
    "color": "var(--fmed-text)",
    "overflowX": "hidden",
    "minWidth": 0,
    "width": "auto",
    "maxWidth": "none",
    "transition": "padding .22s ease, width .22s ease"
  },
  "menuBtn": {
    "width": "100%",
    "minHeight": 48,
    "padding": "0 13px",
    "marginBottom": "0",
    "borderRadius": 10,
    "background": "rgba(12,31,46,.58)",
    "border": "1px solid rgba(88,126,151,.20)",
    "cursor": "pointer",
    "color": "var(--fmed-text)",
    "fontSize": 14,
    "fontWeight": 850,
    "transition": "background .18s ease, color .18s ease, transform .18s ease",
    "display": "flex",
    "alignItems": "center",
    "justifyContent": "flex-start",
    "gap": "9px",
    "appearance": "none",
    "WebkitAppearance": "none",
    "fontFamily": "\"Futura Light\", \"Futura PT\", Futura, \"Trebuchet MS\", Arial, sans-serif",
    "letterSpacing": ".04em",
    "height": "42px",
    "boxShadow": "none",
    "lineHeight": "16px",
    "whiteSpace": "normal",
    "textTransform": "uppercase"
  },
  "menuBtnActive": {
    "background": "linear-gradient(90deg, rgba(20,125,134,.96), rgba(13,99,108,.82))",
    "border": "1px solid rgba(20,125,134,.58)",
    "boxShadow": "0 14px 30px rgba(0,0,0,.28), inset 4px 0 0 rgba(255,255,255,.20)",
    "color": "#FFFFFF"
  },
  "menuIconWrap": {
    "width": "30px",
    "minWidth": "30px",
    "height": "30px",
    "display": "flex",
    "alignItems": "center",
    "justifyContent": "center",
    "borderRadius": "10px",
    "background": "rgba(22,185,201,.10)",
    "fontSize": "21px",
    "color": "var(--fmed-accent-2)",
    "border": "1px solid rgba(31,174,156,.12)"
  },
  "menuInfoIcon": {
    "width": "18px",
    "minWidth": "18px",
    "height": "18px",
    "borderRadius": "999px",
    "display": "inline-flex",
    "alignItems": "center",
    "justifyContent": "center",
    "border": "1px solid rgba(255,255,255,.38)",
    "background": "rgba(255,255,255,.08)",
    "color": "rgba(255,255,255,.90)",
    "fontSize": "11px",
    "fontWeight": 700,
    "lineHeight": 1,
    "textTransform": "lowercase",
    "cursor": "help"
  },
  "menuLabel": {
    "flex": 1,
    "textAlign": "left",
    "whiteSpace": "normal",
    "overflow": "hidden",
    "textOverflow": "ellipsis",
    "fontWeight": 650,
    "overflowWrap": "anywhere",
    "fontSize": "16px",
    "letterSpacing": "0.01em"
  },
  "miniActionBtn": {
    "height": "26px",
    "borderRadius": 12,
    "border": "1px solid var(--fmed-border)",
    "background": "var(--fmed-surface)",
    "color": "var(--fmed-text)",
    "fontSize": "12px",
    "fontWeight": 800,
    "cursor": "pointer",
    "padding": "8px 11px",
    "minHeight": 36,
    "letterSpacing": ".05em",
    "whiteSpace": "normal",
    "WebkitTextFillColor": "var(--fmed-text)"
  },
  "modalCard": {
    "width": "min(1840px, 96vw)",
    "maxHeight": "92vh",
    "overflowY": "auto",
    "overflowX": "hidden",
    "background": "var(--fmed-card-gradient)",
    "border": "1px solid var(--fmed-border)",
    "borderRadius": "26px",
    "padding": "24px",
    "boxShadow": "0 30px 90px rgba(0,0,0,.26)",
    "color": "var(--fmed-text)",
    "boxSizing": "border-box",
    "maxWidth": "1840px",
    "overflow": "auto",
    "height": "92vh"
  },
  "modalOverlay": {
    "position": "fixed",
    "inset": 0,
    "background": "rgba(4, 12, 18, .58)",
    "backdropFilter": "blur(8px)",
    "display": "flex",
    "alignItems": "center",
    "justifyContent": "center",
    "zIndex": 15000,
    "padding": "12px",
    "boxSizing": "border-box",
    "overflow": "hidden"
  },
  "modalOverlayTop": {
    "position": "fixed",
    "inset": 0,
    "background": "rgba(4, 12, 18, .58)",
    "zIndex": 20000,
    "display": "flex",
    "alignItems": "center",
    "justifyContent": "center",
    "padding": "12px",
    "boxSizing": "border-box",
    "backdropFilter": "blur(8px)",
    "overflow": "hidden"
  },
  "modalSmallCard": {
    "width": "min(920px, calc(100vw - 34px))",
    "maxHeight": "calc(100vh - 34px)",
    "overflowY": "auto",
    "overflowX": "hidden",
    "background": "var(--fmed-card-gradient)",
    "borderRadius": 28,
    "padding": "24px",
    "boxShadow": "0 30px 90px rgba(0,0,0,.26)",
    "border": "1px solid var(--fmed-border)",
    "position": "relative",
    "boxSizing": "border-box",
    "color": "var(--fmed-text)",
    "maxWidth": "min(560px, 96vw)",
    "overflow": "auto"
  },
  "modalTitle": {
    "margin": "0 0 22px",
    "fontSize": "clamp(22px, 2.2vw, 32px)",
    "letterSpacing": "-.045em",
    "color": "var(--fmed-text)",
    "fontWeight": 950,
    "fontFamily": "\"Futura Light\", \"Futura PT\", Futura, \"Trebuchet MS\", Arial, sans-serif",
    "maxWidth": "100%",
    "overflowWrap": "anywhere",
    "lineHeight": 1.05,
    "marginBottom": "18px"
  },
  "muted": {
    "color": "#AFC2D3",
    "fontSize": "14px"
  },
  "mutedSmall": {
    "color": "#AFC2D3",
    "fontSize": "12px",
    "fontWeight": 400
  },
  "predictiveHeader": {
    "display": "flex",
    "alignItems": "flex-start",
    "justifyContent": "space-between",
    "gap": "12px",
    "marginBottom": "14px",
    "flexWrap": "wrap"
  },
  "predictiveIcon": {
    "width": "36px",
    "height": "36px",
    "borderRadius": "12px",
    "display": "inline-flex",
    "alignItems": "center",
    "justifyContent": "center",
    "fontSize": "17px"
  },
  "predictiveMetricHint": {
    "fontSize": "10.5px",
    "lineHeight": 1.25,
    "color": "var(--fmed-muted)"
  },
  "predictiveMetricLabel": {
    "fontSize": "11px",
    "lineHeight": 1.2,
    "color": "var(--fmed-muted)",
    "fontWeight": 600,
    "letterSpacing": ".06em",
    "textTransform": "uppercase"
  },
  "predictivePanel": {
    "background": "linear-gradient(180deg, rgba(255,255,255,.98) 0%, rgba(246,250,252,.98) 100%)",
    "borderWidth": "1px",
    "borderStyle": "solid"
  },
  "predictiveProgressFill": {
    "display": "block",
    "height": "100%",
    "borderRadius": "inherit",
    "minWidth": "4px",
    "transition": "width .25s ease"
  },
  "predictiveProgressTrack": {
    "width": "78%",
    "maxWidth": "150px",
    "height": "7px",
    "borderRadius": "999px",
    "overflow": "hidden",
    "background": "rgba(15,23,42,.10)",
    "marginTop": "2px"
  },
  "predictiveSubtitle": {
    "fontSize": "12px",
    "lineHeight": 1.4,
    "color": "var(--fmed-muted)",
    "maxWidth": "460px"
  },
  "predictiveSummaryPill": {
    "minHeight": "30px",
    "padding": "6px 10px",
    "borderRadius": "999px",
    "fontSize": "11px",
    "lineHeight": 1.2,
    "fontWeight": 600,
    "letterSpacing": ".03em",
    "textTransform": "uppercase",
    "whiteSpace": "nowrap"
  },
  "primaryBtn": {
    "minHeight": 42,
    "padding": "10px 15px",
    "borderRadius": 10,
    "border": "1px solid rgba(124,199,205,.22)",
    "background": "var(--fmed-btn)",
    "color": "#FFFFFF",
    "fontSize": "13px",
    "fontWeight": 950,
    "cursor": "pointer",
    "boxShadow": "var(--fmed-btn-shadow)",
    "whiteSpace": "nowrap",
    "overflow": "visible",
    "lineHeight": "17px",
    "letterSpacing": ".04em",
    "WebkitTextFillColor": "#FFFFFF",
    "textTransform": "uppercase"
  },
  "recommendationBox": {
    "border": "1px solid rgba(0,0,0,.08)",
    "borderRadius": "12px",
    "padding": "20px",
    "minHeight": "74px",
    "background": "var(--fmed-card-gradient)",
    "color": "var(--fmed-text)",
    "fontSize": "11.5px",
    "lineHeight": "1.28",
    "fontWeight": 400,
    "boxShadow": "none",
    "overflowWrap": "anywhere"
  },
  "recommendationBoxCalculation": {
    "background": "linear-gradient(180deg,#FFFAEB 0%,#FEF0C7 100%)",
    "borderColor": "#FEDF89",
    "boxShadow": "inset 4px 0 0 #F79009"
  },
  "recommendationBoxInfo": {
    "background": "linear-gradient(180deg,#F5FAFF 0%,#EFF8FF 100%)",
    "borderColor": "#B2DDFF",
    "boxShadow": "inset 4px 0 0 #2E90FA"
  },
  "recommendationBoxTechnical": {
    "background": "linear-gradient(180deg,#F9F5FF 0%,#F4EBFF 100%)",
    "borderColor": "#D6BBFB",
    "boxShadow": "inset 4px 0 0 #9E77ED"
  },
  "recommendationGrid": {
    "display": "grid",
    "gridTemplateColumns": "1fr 1fr 1fr",
    "gap": "8px"
  },
  "recommendationPanel": {
    "background": "var(--fmed-surface-solid)",
    "border": "1px solid rgba(20,32,51,.08)",
    "borderRadius": "12px",
    "padding": "18px",
    "marginBottom": "8px",
    "boxShadow": "0 3px 10px rgba(15,23,42,.04)"
  },
  "recommendationTitle": {
    "color": "#6F846C",
    "fontWeight": 400,
    "textTransform": "uppercase",
    "marginBottom": "4px",
    "fontSize": "13px"
  },
  "rowActionGroup": {
    "display": "flex",
    "flexDirection": "row",
    "gap": 8,
    "alignItems": "center",
    "justifyContent": "flex-end",
    "flexWrap": "nowrap"
  },
  "saveBtn": {
    "padding": "14px 22px",
    "borderRadius": "14px",
    "border": "1px solid rgba(31,174,156,.46)",
    "background": "linear-gradient(135deg,#1FAE9C,#1FAE9C)",
    "color": "#02131F",
    "fontWeight": 900,
    "cursor": "pointer",
    "boxShadow": "0 16px 34px rgba(31,174,156,.18)",
    "minHeight": "44px",
    "fontSize": "13px",
    "lineHeight": "16px",
    "letterSpacing": ".05em",
    "whiteSpace": "normal"
  },
  "secondaryBtn": {
    "minHeight": 42,
    "borderRadius": 10,
    "border": "1px solid var(--fmed-border)",
    "background": "rgba(8,26,40,.92)",
    "color": "var(--fmed-text)",
    "fontWeight": 950,
    "fontSize": "13px",
    "fontFamily": "\"Futura Light\", \"Futura PT\", Futura, \"Trebuchet MS\", Arial, sans-serif",
    "cursor": "pointer",
    "padding": "10px 14px",
    "whiteSpace": "nowrap",
    "overflow": "visible",
    "boxShadow": "var(--fmed-card-shadow-soft)",
    "lineHeight": "17px",
    "letterSpacing": ".04em",
    "WebkitTextFillColor": "var(--fmed-text)",
    "textTransform": "uppercase"
  },
  "sectionTitle": {
    "marginTop": "0",
    "marginBottom": "10px",
    "fontSize": "18px",
    "fontWeight": 500,
    "color": "var(--fmed-text)",
    "lineHeight": "24px",
    "letterSpacing": 0
  },
  "select": {
    "height": "42px",
    "padding": "10px 12px",
    "borderRadius": 13,
    "border": "1px solid var(--fmed-border)",
    "background": "var(--fmed-surface-solid)",
    "color": "var(--fmed-text)",
    "fontSize": "13px",
    "outline": "none",
    "boxShadow": "none",
    "textTransform": "none",
    "fontStyle": "normal",
    "minWidth": 0,
    "boxSizing": "border-box",
    "minHeight": 42,
    "fontWeight": 780,
    "width": "100%"
  },
  "sidebar": {
    "width": "250px",
    "minWidth": "250px",
    "height": "100vh",
    "backgroundColor": "transparent",
    "backgroundImage": "var(--fmed-sidebar-bg)",
    "backgroundSize": "cover",
    "backgroundPosition": "left bottom",
    "backgroundRepeat": "no-repeat",
    "borderRight": "1px solid var(--fmed-border)",
    "boxShadow": "12px 0 36px rgba(0,0,0,.16)",
    "padding": "22px 16px 18px",
    "boxSizing": "border-box",
    "position": "relative",
    "overflow": "hidden",
    "display": "flex",
    "flexDirection": "column",
    "background": "var(--fmed-sidebar-bg)",
    "color": "var(--fmed-sidebar-text)",
    "overflowX": "hidden",
    "textTransform": "uppercase"
  },
  "sidebarActionRow": {
    "display": "grid",
    "gridTemplateColumns": "1fr",
    "gap": "7px",
    "width": "100%"
  },
  "sidebarBottomPanel": {
    "flex": "0 0 auto",
    "display": "flex",
    "flexDirection": "column",
    "gap": "7px",
    "paddingTop": "14px",
    "borderTop": "1px solid rgba(31,174,156,.12)",
    "flexShrink": 0,
    "background": "rgba(255,255,255,.09)",
    "border": "1px solid rgba(255,255,255,.12)",
    "color": "var(--fmed-sidebar-text)"
  },
  "sidebarBottomPanelCollapsed": {
    "alignItems": "center",
    "width": "100%"
  },
  "sidebarBrandLink": {
    "display": "block",
    "textDecoration": "none",
    "color": "inherit",
    "cursor": "pointer"
  },
  "sidebarBrandLinkCollapsed": {
    "justifyContent": "center",
    "alignItems": "center",
    "width": "100%",
    "minHeight": 46,
    "padding": 0
  },
  "sidebarCollapseBtn": {
    "width": 42,
    "height": 38,
    "borderRadius": 14,
    "border": "1px solid rgba(0,122,140,.18)",
    "background": "rgba(255,255,255,.78)",
    "color": "#083B46",
    "cursor": "pointer",
    "fontSize": 18,
    "boxShadow": "0 8px 18px rgba(6,34,55,.10)"
  },
  "sidebarCollapseTop": {
    "display": "flex",
    "justifyContent": "flex-end",
    "marginBottom": "8px"
  },
  "sidebarCollapseTopCentered": {
    "display": "flex",
    "justifyContent": "center",
    "width": "100%",
    "marginBottom": "8px"
  },
  "sidebarCollapsed": {
    "width": "86px",
    "minWidth": "86px",
    "padding": "18px 12px",
    "alignItems": "center",
    "maxWidth": "86px",
    "flex": "0 0 86px",
    "overflow": "hidden"
  },
  "sidebarDivider": {
    "margin": "10px 0",
    "opacity": 0.28,
    "borderColor": "rgba(255,255,255,.16)"
  },
  "sidebarLogoutSmallBtnLight": {
    "minHeight": "36px",
    "height": "36px",
    "padding": "0 8px",
    "borderRadius": "14px",
    "border": "1px solid rgba(9, 54, 78, .10)",
    "background": "#FFFFFF",
    "color": "#082033",
    "cursor": "pointer",
    "display": "inline-flex",
    "alignItems": "center",
    "justifyContent": "center",
    "gap": "6px",
    "fontSize": "10px",
    "lineHeight": "12px",
    "fontWeight": 500,
    "letterSpacing": ".04em",
    "textTransform": "uppercase",
    "boxShadow": "0 10px 24px rgba(8,32,51,.06)",
    "width": "100%"
  },
  "sidebarNav": {
    "display": "flex",
    "flexDirection": "column",
    "gap": 8,
    "marginTop": "28px",
    "width": "100%",
    "flex": "1 1 auto",
    "minHeight": 0,
    "overflowY": "auto",
    "paddingBottom": "8px",
    "scrollbarWidth": "thin",
    "paddingRight": "2px",
    "overflowX": "hidden"
  },
  "sidebarRoleHintLight": {
    "marginTop": 10,
    "padding": "0 8px",
    "borderRadius": "10px",
    "background": "rgba(255,255,255,.07)",
    "border": "1px solid rgba(255,255,255,.13)",
    "color": "rgba(255,255,255,0.72)",
    "fontSize": "9px",
    "letterSpacing": ".06em",
    "textTransform": "uppercase",
    "lineHeight": "12px",
    "textAlign": "center",
    "minHeight": "28px",
    "fontWeight": 500,
    "height": "28px",
    "display": "none"
  },
  "sidebarUserAvatarLight": {
    "width": "34px",
    "height": "34px",
    "borderRadius": "12px",
    "display": "flex",
    "alignItems": "center",
    "justifyContent": "center",
    "background": "linear-gradient(135deg, rgba(18,184,200,.16), rgba(18,184,200,.06))",
    "color": "#087A8D",
    "fontSize": "14px",
    "fontWeight": 500,
    "flex": "0 0 auto",
    "minWidth": "34px",
    "border": "1px solid rgba(18,184,200,.18)",
    "boxShadow": "none"
  },
  "sidebarUserCardLight": {
    "display": "flex",
    "alignItems": "center",
    "gap": "10px",
    "padding": "10px 12px",
    "borderRadius": "16px",
    "background": "linear-gradient(145deg, #FFFFFF 0%, #F5FBFD 100%)",
    "border": "1px solid rgba(9, 54, 78, .10)",
    "color": "#082033",
    "backdropFilter": "blur(8px)",
    "minHeight": "58px",
    "boxShadow": "0 12px 28px rgba(8, 32, 51, .08)"
  },
  "sidebarUserInfo": {
    "minWidth": 0,
    "flex": 1
  },
  "sidebarUserNameLight": {
    "color": "#082033",
    "fontSize": "12px",
    "lineHeight": "15px",
    "letterSpacing": "0.04em",
    "whiteSpace": "nowrap",
    "overflow": "hidden",
    "textOverflow": "ellipsis",
    "fontWeight": 600
  },
  "sidebarUserRoleLight": {
    "color": "#637287",
    "fontSize": "9px",
    "lineHeight": "12px",
    "letterSpacing": ".08em",
    "textTransform": "uppercase",
    "whiteSpace": "nowrap",
    "overflow": "hidden",
    "textOverflow": "ellipsis",
    "opacity": 1
  },
  "table": {
    "width": "100%",
    "borderCollapse": "separate",
    "fontSize": 12,
    "color": "var(--fmed-text)",
    "borderSpacing": 0,
    "background": "transparent",
    "WebkitTextFillColor": "var(--fmed-text)",
    "textTransform": "uppercase"
  },
  "tableWrapCompact": {
    "width": "100%",
    "overflowX": "auto",
    "maxHeight": "52vh",
    "overflowY": "auto",
    "marginTop": "12px",
    "border": "1px solid var(--fmed-border)",
    "borderRadius": 14,
    "background": "#0A1B29",
    "boxShadow": "var(--fmed-card-shadow-soft)",
    "overflow": "auto",
    "color": "var(--fmed-text)"
  },
  "td": {
    "padding": "15px 14px",
    "borderBottom": "1px solid rgba(88,126,151,.20)",
    "fontSize": 12,
    "fontWeight": 800,
    "color": "var(--fmed-text)",
    "lineHeight": 1.35,
    "whiteSpace": "normal",
    "overflowWrap": "anywhere",
    "verticalAlign": "middle",
    "minHeight": "40px",
    "borderColor": "rgba(31,174,156,.12)",
    "background": "transparent",
    "textTransform": "uppercase"
  },
  "th": {
    "padding": "14px 14px",
    "background": "#0F2637",
    "color": "var(--fmed-text)",
    "textAlign": "left",
    "fontSize": 12,
    "fontWeight": 950,
    "textTransform": "uppercase",
    "borderBottom": "1px solid var(--fmed-border)",
    "height": "40px",
    "lineHeight": 1.15,
    "letterSpacing": ".04em",
    "whiteSpace": "nowrap",
    "borderColor": "rgba(31,174,156,.16)",
    "position": "sticky",
    "top": 0,
    "zIndex": 3
  },
  "themeLightVars": {
    "--fmed-bg": "#F5F1E8",
    "--fmed-surface": "rgba(252,250,245,.96)",
    "--fmed-surface-solid": "#FCFAF5",
    "--fmed-surface-soft": "#F7F2E8",
    "--fmed-text": "#1F2933",
    "--fmed-muted": "#667085",
    "--fmed-border": "rgba(31,78,109,.14)",
    "--fmed-accent": "#0F7C90",
    "--fmed-accent-2": "#0A5968",
    "--fmed-sand": "#12314A",
    "--fmed-sage": "#6DB193",
    "--fmed-sage-strong": "#165A52",
    "--fmed-primary": "#0F7C90",
    "--fmed-primary-2": "#0A5968",
    "--fmed-highlight": "#6DB193",
    "--fmed-btn": "linear-gradient(135deg, #0F7C90 0%, #0A5968 100%)",
    "--fmed-btn-shadow": "0 16px 34px rgba(31,78,109,.20)",
    "--fmed-main-bg": "linear-gradient(180deg, #F5F1E8 0%, #FBF8F1 52%, #EFE7DA 100%)",
    "--fmed-sidebar-bg": "linear-gradient(180deg, #173B50 0%, #1F4E6D 55%, #16394E 100%)",
    "--fmed-header-bg": "rgba(252,250,245,.94)",
    "--fmed-header-inner": "linear-gradient(145deg, rgba(252,250,245,.98), rgba(247,242,232,.94))",
    "--fmed-card-gradient": "linear-gradient(145deg, rgba(252,250,245,.98), rgba(247,242,232,.95))",
    "--fmed-soft-gradient": "linear-gradient(145deg, rgba(255,255,255,.84), rgba(247,242,232,.92))",
    "--fmed-alert-red-bg": "linear-gradient(135deg, rgba(83,30,25,.96), rgba(13,34,52,.94))",
    "--fmed-alert-orange-bg": "linear-gradient(135deg, rgba(83,55,20,.96), rgba(13,34,52,.94))",
    "--fmed-alert-gold-bg": "linear-gradient(135deg, rgba(18,49,74,.98), rgba(13,34,52,.94))",
    "--fmed-danger-bg": "#4A1F1B",
    "--fmed-danger-text": "#FF8A7A",
    "--fmed-danger-border": "rgba(255,138,122,.45)",
    "--fmed-soft-btn-bg": "#12314A",
    "--fmed-soft-btn-text": "#F4F8F7",
    "--fmed-panel-gradient": "linear-gradient(180deg, rgba(8,49,76,.98) 0%, rgba(5,36,56,.98) 100%)",
    "--fmed-hero-bg": "linear-gradient(135deg, rgba(8,49,76,.98) 0%, rgba(4,30,48,.98) 100%)",
    "--fmed-hero-border": "rgba(177,215,238,.24)",
    "--fmed-icon-bg": "rgba(242,184,75,.14)",
    "--fmed-icon-text": "#F2B84B",
    "--fmed-trust-border": "rgba(177,215,238,.22)",
    "--fmed-subtle": "#8793A0",
    "--fmed-card-shadow": "0 18px 45px rgba(31,78,109,.12)",
    "--fmed-card-shadow-soft": "0 10px 24px rgba(31,78,109,.08)",
    "--fmed-sidebar-text": "#F8FAFC",
    "--fmed-sidebar-muted": "rgba(248,250,252,.68)",
    "--fmed-border-strong": "rgba(23,33,43,.20)",
    "--fmed-blue": "#165A52",
    "--fmed-success": "#2F8F67",
    "--fmed-warning": "#D48A18",
    "--fmed-danger": "#C9434F",
    "--fmed-btn-blue": "linear-gradient(135deg,#169C8F 0%,#165A52 100%)",
    "--fmed-focus": "0 0 0 3px rgba(127,160,136,.22)",
    "--fmed-surface-raised": "#FFFFFF",
    "--fmed-btn-secondary": "linear-gradient(135deg,#7FA088 0%,#5F8068 100%)"
  },
  "tr": {
    "borderBottom": "1px solid var(--fmed-border)",
    "minHeight": "40px",
    "background": "var(--fmed-surface-solid)",
    "color": "#E8F7FF"
  }
};

export default styles;
